name: Minimal Workflow for Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  simple-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Hello, this is a minimal workflow running on a self-hosted runner!"