name: Test actions/setup-node without preexisting Node.js

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-setup-node:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Node.js is not preinstalled
        run: |
          if command -v node; then
            echo "Node.js is already installed on this runner."
            exit 1
          else
            echo "Node.js is not installed, proceeding with the test."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Verify Node.js installation
        run: |
          if command -v node; then
            echo "Node.js has been installed successfully."
          else
            echo "Node.js installation failed."
            exit 1
          fi